model:
  model_root: /workspace/docker_share
  model_size: base
  model_patch: 16
  image_size: 256

predict:
  ckpt: outputs/model/best_model.pt
  input_txt: test.txt
  output_txt: result.txt

decoder:
  query_num: 70

runtime:
  batch_size: 64
  num_workers: 4