model:
  model_root: /workspace/docker_share
  model_size: base
  model_patch: 16
  image_size: 256
  local_files_only: true

dataset:
  train_txt: train.txt
  val_txt: val.txt
  labels_txt: labels.txt

training:
  batch_size: 32
  epochs: 20
  lr: 2e-5
  weight_decay: 1e-4
  warmup_ratio: 0.05

ml_decoder:
  query_num: 70
  embed_dim: 768

augmentation:
  randaugment: true
  cutout: true

loss:
  type: asl
  gamma_pos: 0
  gamma_neg: 4

ema:
  enabled: true
  decay: 0.9997

save:
  output_dir: outputs/siglip2_base_patch16_256
  save_best: true